# Generated by Django 4.2.7 on 2026-01-22 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BahanBaku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bahan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BahanBakuMasuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_masuk', models.DateField(default=django.utils.timezone.now)),
                ('jumlah_pcs', models.PositiveIntegerField(default=0)),
                ('jumlah_m3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sisa_pcs', models.PositiveIntegerField(default=0)),
                ('sisa_m3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Validasi'), ('valid', 'Disetujui Accounting'), ('reject', 'Ditolak Accounting')], default='pending', max_length=10)),
                ('catatan_accounting', models.TextField(blank=True, null=True)),
                ('bahan_baku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bahanbaku')),
            ],
            options={
                'ordering': ['tanggal_masuk'],
            },
        ),
        migrations.CreateModel(
            name='HasilProduksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_produksi', models.DateField()),
                ('tebal', models.DecimalField(decimal_places=4, max_digits=10)),
                ('lebar', models.DecimalField(decimal_places=4, max_digits=10)),
                ('panjang', models.DecimalField(decimal_places=4, max_digits=10)),
                ('jumlah_pcs', models.PositiveIntegerField()),
                ('jumlah_m3', models.DecimalField(decimal_places=4, max_digits=12)),
                ('sisa_pcs', models.PositiveIntegerField()),
                ('sisa_m3', models.DecimalField(decimal_places=4, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='NamaHasilProduksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_hasil_produksi', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pembeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pembeli', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Penjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_penjualan', models.DateField(default=django.utils.timezone.now)),
                ('pcs', models.PositiveIntegerField(default=0)),
                ('m3', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('total_harga', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('status_invoice', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Validasi'), ('valid', 'Disetujui Accounting'), ('reject', 'Ditolak Accounting')], default='pending', max_length=10)),
                ('catatan_accounting', models.TextField(blank=True, null=True)),
                ('hasil_produksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penjualan', to='core.hasilproduksi')),
                ('pembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pembeli')),
            ],
        ),
        migrations.CreateModel(
            name='ProsesProduksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_produksi', models.DateField(default=django.utils.timezone.now)),
                ('keterangan', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_supplier', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('kontak', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ValidasiAccounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_validasi', models.CharField(choices=[('pengadaan', 'Pengadaan Barang'), ('penjualan', 'Invoice Penjualan')], max_length=30)),
                ('tanggal_validasi', models.DateField(default=django.utils.timezone.now)),
                ('disetujui', models.BooleanField(default=False)),
                ('catatan', models.TextField(blank=True)),
                ('bahan_baku_masuk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bahanbakumasuk')),
                ('penjualan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.penjualan')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('purchasing', 'Purchasing'), ('produksi', 'Produksi'), ('penjualan', 'Penjualan'), ('accounting', 'Accounting')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PemakaianBahanBaku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_pcs', models.PositiveIntegerField(default=0)),
                ('jumlah_m3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bahan_baku_masuk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bahanbakumasuk')),
                ('proses_produksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prosesproduksi')),
            ],
        ),
        migrations.AddField(
            model_name='hasilproduksi',
            name='nama_hasil_produksi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.namahasilproduksi'),
        ),
        migrations.AddField(
            model_name='hasilproduksi',
            name='pemakaian_bahan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pemakaianbahanbaku'),
        ),
        migrations.AddField(
            model_name='hasilproduksi',
            name='proses_produksi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prosesproduksi'),
        ),
        migrations.AddField(
            model_name='hasilproduksi',
            name='quality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quality'),
        ),
        migrations.AddField(
            model_name='bahanbakumasuk',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supplier'),
        ),
    ]
