# Generated by Django 4.2.7 on 2026-01-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penjualan',
            name='tanggal_penjualan',
            field=models.DateField(),
        ),
    ]
