# Generated by Django 4.2.7 on 2026-02-25 16:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_penjualan_tanggal_penjualan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hasilproduksi',
            name='quality',
        ),
        migrations.CreateModel(
            name='QualityControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_qc', models.DateField(default=django.utils.timezone.now)),
                ('jumlah_pcs', models.PositiveIntegerField()),
                ('jumlah_m3', models.DecimalField(decimal_places=4, max_digits=12)),
                ('catatan', models.TextField(blank=True)),
                ('hasil_produksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc', to='core.hasilproduksi')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quality')),
            ],
        ),
    ]
