# Generated by Django 4.2.7 on 2026-02-25 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_hasilproduksi_quality_qualitycontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasilproduksi',
            name='quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.quality'),
        ),
    ]
