# Generated by Django 4.2.7 on 2026-02-25 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hasilproduksi_quality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualitycontrol',
            name='jumlah_m3',
        ),
        migrations.RemoveField(
            model_name='qualitycontrol',
            name='jumlah_pcs',
        ),
        migrations.RemoveField(
            model_name='qualitycontrol',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='qualitycontrol',
            name='tanggal_qc',
        ),
        migrations.AddField(
            model_name='qualitycontrol',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approve', 'Approve'), ('reject', 'Reject')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='qualitycontrol',
            name='tanggal_validasi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualitycontrol',
            name='catatan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualitycontrol',
            name='hasil_produksi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qc', to='core.hasilproduksi'),
        ),
    ]
