# Generated by Django 4.2.7 on 2026-02-25 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_qualitycontrol_jumlah_m3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualitycontrol',
            name='status',
        ),
        migrations.AddField(
            model_name='qualitycontrol',
            name='quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.quality'),
        ),
    ]
