# Generated by Django 4.2.7 on 2026-03-06 10:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_qualitycontrol_status_qualitycontrol_quality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_invoice', models.CharField(max_length=50, unique=True)),
                ('tanggal_invoice', models.DateField(default=django.utils.timezone.now)),
                ('total_tagihan', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('belum_bayar', 'Belum Dibayar'), ('sebagian', 'Dibayar Sebagian'), ('lunas', 'Lunas')], default='belum_bayar', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='penjualan',
            name='status_invoice',
        ),
        migrations.AlterField(
            model_name='penjualan',
            name='total_harga',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('jumlah_bayar', models.DecimalField(decimal_places=2, max_digits=15)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to='core.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='penjualan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='core.penjualan'),
        ),
    ]
