# Generated by Django 4.2.7 on 2026-03-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_invoice_remove_penjualan_status_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penjualan',
            name='harga_satuan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
