# Generated by Django 4.2.7 on 2026-04-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_penjualan_harga_satuan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penjualan',
            name='total_harga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
