# Generated by Django 4.2.7 on 2026-04-08 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_penjualan_total_harga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penjualan',
            name='harga_satuan',
        ),
    ]
