# Generated by Django 4.2.7 on 2026-04-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_invoicepembelian_pembayaranpembelian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasilproduksi',
            name='jumlah_m3',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='hasilproduksi',
            name='lebar',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hasilproduksi',
            name='panjang',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hasilproduksi',
            name='sisa_m3',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='hasilproduksi',
            name='tebal',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
