# Generated by Django 4.2.7 on 2026-04-09 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_alter_hasilproduksi_jumlah_m3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AkunKeuangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('tipe', models.CharField(choices=[('aset', 'Aset'), ('kewajiban', 'Kewajiban'), ('ekuitas', 'Ekuitas'), ('pendapatan', 'Pendapatan'), ('beban', 'Beban')], max_length=20)),
                ('kelompok', models.CharField(choices=[('kas', 'Kas & Setara Kas'), ('piutang', 'Piutang Usaha'), ('persediaan', 'Persediaan'), ('aset_tetap', 'Aset Tetap'), ('hutang_dagang', 'Hutang Dagang'), ('hutang_lain', 'Kewajiban Lain'), ('modal', 'Modal'), ('laba_ditahan', 'Laba Ditahan'), ('pendapatan_penjualan', 'Pendapatan Penjualan'), ('pendapatan_lain', 'Pendapatan Lain'), ('hpp', 'Harga Pokok Penjualan'), ('beban_operasional', 'Beban Operasional'), ('beban_lain', 'Beban Lain'), ('barang_dalam_proses', 'Barang Dalam Proses'), ('persediaan_barang_jadi', 'Persediaan Barang Jadi')], max_length=30)),
                ('saldo_normal', models.CharField(choices=[('debit', 'Debit'), ('kredit', 'Kredit')], max_length=6)),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JurnalAkuntansi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe_transaksi', models.CharField(choices=[('pembelian', 'Pembelian'), ('penjualan', 'Penjualan'), ('pembayaran', 'Pembayaran'), ('produksi', 'Produksi')], max_length=20)),
                ('subtipe_produksi', models.CharField(blank=True, choices=[('proses', 'Proses Produksi'), ('barang_jadi', 'Barang Jadi')], max_length=20, null=True)),
                ('nomor_jurnal', models.CharField(max_length=30, unique=True)),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('keterangan', models.TextField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('periode', models.CharField(max_length=7)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hasil_produksi', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hasilproduksi')),
                ('pemakaian_bahan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pemakaianbahanbaku')),
                ('pembayaran', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pembayaran')),
                ('pembelian', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bahanbakumasuk')),
                ('penjualan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.penjualan')),
            ],
        ),
        migrations.CreateModel(
            name='JurnalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('kredit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.akunkeuangan')),
                ('jurnal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.jurnalakuntansi')),
            ],
        ),
    ]
