# Generated by Django 4.2.7 on 2026-04-09 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_akunkeuangan_jurnalakuntansi_jurnaldetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='bahanbakumasuk',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
