# Generated by Django 4.2.7 on 2026-04-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_bahanbakumasuk_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='penjualan',
            name='no_surat_jalan',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
