# Generated by Django 4.2.7 on 2026-04-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_penjualan_no_surat_jalan'),
    ]

    operations = [
        migrations.AddField(
            model_name='penjualan',
            name='no_po',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='penjualan',
            name='nopol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='penjualan',
            name='no_surat_jalan',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
