# Generated by Django 4.2.7 on 2026-04-24 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_penjualan_no_po_penjualan_nopol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='penjualan',
        ),
        migrations.RemoveField(
            model_name='jurnalakuntansi',
            name='dibuat_oleh',
        ),
        migrations.RemoveField(
            model_name='jurnalakuntansi',
            name='hasil_produksi',
        ),
        migrations.RemoveField(
            model_name='jurnalakuntansi',
            name='pemakaian_bahan',
        ),
        migrations.RemoveField(
            model_name='jurnalakuntansi',
            name='pembayaran',
        ),
        migrations.RemoveField(
            model_name='jurnalakuntansi',
            name='pembelian',
        ),
        migrations.RemoveField(
            model_name='jurnalakuntansi',
            name='penjualan',
        ),
        migrations.RemoveField(
            model_name='jurnaldetail',
            name='akun',
        ),
        migrations.RemoveField(
            model_name='jurnaldetail',
            name='jurnal',
        ),
        migrations.RemoveField(
            model_name='pembayaran',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='AkunKeuangan',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='JurnalAkuntansi',
        ),
        migrations.DeleteModel(
            name='JurnalDetail',
        ),
        migrations.DeleteModel(
            name='Pembayaran',
        ),
    ]
