# Generated by Django 4.2.7 on 2026-04-24 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_invoice_penjualan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembayaranpembelian',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='InvoicePembelian',
        ),
        migrations.DeleteModel(
            name='PembayaranPembelian',
        ),
    ]
