# Generated by Django 4.2.7 on 2026-05-02 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_pembayaranpembelian_invoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bahanbakumasuk',
            name='catatan_accounting',
        ),
        migrations.RemoveField(
            model_name='bahanbakumasuk',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bahanbakumasuk',
            name='status',
        ),
        migrations.RemoveField(
            model_name='penjualan',
            name='catatan_accounting',
        ),
        migrations.RemoveField(
            model_name='penjualan',
            name='no_po',
        ),
        migrations.RemoveField(
            model_name='penjualan',
            name='no_surat_jalan',
        ),
        migrations.RemoveField(
            model_name='penjualan',
            name='nopol',
        ),
        migrations.RemoveField(
            model_name='penjualan',
            name='status',
        ),
    ]
