# Generated by Django 4.2.7 on 2026-05-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_bahanbakumasuk_catatan_accounting_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValidasiAccounting',
        ),
    ]
