# Generated by Django 4.2.7 on 2026-06-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_delete_validasiaccounting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bahanbakumasuk',
            name='jumlah_m3',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bahanbakumasuk',
            name='sisa_m3',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pemakaianbahanbaku',
            name='jumlah_m3',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='penjualan',
            name='m3',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
