# Generated by Django 4.2.7 on 2026-06-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_bahanbakumasuk_jumlah_m3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('purchasing', 'Purchasing'), ('produksi', 'Produksi'), ('penjualan', 'Penjualan'), ('qualitycontrol', 'Quality Control')], max_length=20),
        ),
    ]
